# Generated by Django 5.2.6 on 2025-09-23 22:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('celana', 'Celana'), ('sarung_tangan', 'Sarung Tangan'), ('sepatu', 'Sepatu'), ('pelindung', 'Pelindung (siku/lutut/pinggul)'), ('kaos_kaki', 'Kaos Kaki'), ('aksesoris', 'Aksesoris')], default='jersey', max_length=50)),
                ('thumbnail', models.URLField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL')], default='l', max_length=20)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
